# SPDX-FileCopyrightText: 2026-present Arthit Suriyawongkul
# SPDX-License-Identifier: Apache-2.0

name: Lint and format

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  ruff:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install Ruff
        run: |
          pip install --upgrade pip
          pip install ".[java]" --group lint

      - name: Ruff linter
        run: |
          ruff check src/ tests/

      - name: Pylint
        run: |
          pylint src/

      - name: Ruff formatter check
        run: |
          ruff format --check src/ tests/
